name: Deploy Tennis WebAPI to Azure Free Tier
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: tennis-api-webapp
  AZURE_RESOURCE_GROUP: reg_apps  
  DOTNET_VERSION: '8.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Publish .NET Project
      run: |
        dotnet publish TennisProject/Tennis.API.Presentation -c Release -o ./publish
        
    - name: Create ZIP package
      run: |
        cd ./publish
        zip -r ../app.zip .
        cd ..
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        auth-type: SERVICE_PRINCIPAL
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      env:
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./app.zip
