name: Deploy Tennis WebAPI to Azure Free Tier

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: tennis-api-webapp
  DOTNET_VERSION: '8.x'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Publish .NET Project
      run: |
        dotnet publish TennisProject/Tennis.API.Presentation -c Release -o ./publish
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create ZIP package
      run: |
        cd ./publish
        zip -r ../app.zip .
        cd ..
    
    - name: Deploy using Azure CLI
      run: |
        az webapp deployment source config-zip --name ${{ env.AZURE_WEBAPP_NAME }} --src app.zip
