name: Deploy Tennis WebAPI to Azure Free Tier

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: tennis-api-webapp
  AZURE_RESOURCE_GROUP: reg_apps  
  DOTNET_VERSION: '8.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish .NET Project
      run: |
        dotnet publish TennisProject/Tennis.API.Presentation -c Release -o ./publish

    - name: Azure CLI Login
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az login --service-principal \
            --username ${{ secrets.AZURE_APP_ID }} \
            --password ${{ secrets.AZURE_PASSWORD }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account show  # Vérifie que la connexion est réussie

    - name: Create ZIP package
      run: |
        cd ./publish
        zip -r ../app.zip .  # Crée l'archive ZIP
        cd ..  # Reviens au répertoire racine
        ls -al  # Affiche le contenu pour vérifier que app.zip a bien été créé

    - name: Deploy using Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az webapp deployment source config-zip \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --src app.zip
