name: Deploy Tennis WebAPI to Azure Free Tier
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: tennis-api-webapp
  AZURE_RESOURCE_GROUP: reg_apps  
  DOTNET_VERSION: '8.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Publish .NET Project
      run: |
        dotnet publish TennisProject/Tennis.API.Presentation -c Release -o ./publish
        
    - name: Create ZIP package
      run: |
        cd ./publish
        zip -r ../app.zip .
        cd ..

    # Utilisation de la commande Azure CLI directement
    - name: Azure Login with CLI
      run: |
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config-zip \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --src app.zip
